### ISSUE TITLE
Fix bnfrdr, Windows 2000/cygwin/minGW

### ISSUE THREAD

**Issue by svigerske** [coin-or/DyLP#5]
Issue created by migration from Trac.

Original creator: @LouHafer

Original creation time: 2006-07-02 20:20:59

Assignee: @LouHafer

Version: 

Dylp's command parser, bnfrdr, does not play nicely with gcc in the cygwin/minGW environment. No errors/warnings during nonoptimised build, but any call to parse fails. At higher optimisation levels, the compiler warns that type punning breaks strict aliasing rules. The gcc documentation for strict aliasing warns against the coding style used in dylp to return results from a parse, but the problem should occur only when optimising. Error does not occur in optimised or nonoptimised builds in unix environments (Linux, Solaris).

Needs to be debugged in a Cygwin/minGW environment. Volunteers welcome.

**Comment by LouHafer** [comment]
I'm seeing intermittent failures in the Windows mingw x86_64 CI builds. Something to pursue, but not high priority just at the moment.

**Comment by LouHafer** [comment]
So it turns out the problem didn't go away, but while I was updating the examples to work in the Windows / MinGW64 environment, I found the problem. Dylp's parser uses ftell / fseek to back up over an unsuccessful parse attempt and this does not work well with the Windows text mode translation of crlf <-> lf. If the command file is opened in binary mode, the parser works. Various commits 220714 fix the problem.

**Comment by tkralphs** [comment]
Wow, a fix 16 years later. Not sure it's a record, but certainly up there!

**Comment by LouHafer** [comment]
> Wow, a fix 16 years later. Not sure it's a record, but certainly up there!

Antique restoration is a long-standing hobby or mine.   :-)
